sudo: required
services:
  - docker

before_install:
  - docker build -t xdinh99z/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true xdinh99z/react-test npm test -- --coverage

after_sucess:
  - docker build -t xdinh99z/multi-client ./client
  - docker build -t xdinh99z/multi-nginx ./nginx
  - docker build -t xdinh99z/multi-server ./server
  - docker build -t xdinh99z/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Log in to the docker CLI
  - docker push xdinh99z/multi-client
  - docker push xdinh99z/multi-nginx 
  - docker push xdinh99z/multi-server
  - docker push xdinh99z/multi-worker
  #login test auto

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: Multidockerenv-env
  bucket_name:  elasticbeanstalk-us-east-2-108927654363
  bucket_path: docker-multi
  skip_cleanup: true
  on: 
    branch: master
  access_key_id: $AWS_KEY_ACCESS
  secret_access_key: $AWS_SECRET_KEY